### ISSUE TITLE
Forward Momentum has stalled

### ISSUE THREAD

**Issue by frankhale** [pojala/electrino#13]
I hate to be that guy, however, the community has shown interest but things are not moving due to pull requests not being merged or commented on and issues sitting for extended periods of time. Let's not let this sit for too long or people that are interested will simply give up and move on.

**Comment by amilajack** [comment]
Has anyone asked the owner for write permissions?

update: just reached out to the owner about this. Hopefully he gets in touch soon

**Comment by JakeChampion** [comment]
It last had a commit to master 17 days, I wouldn't presume development has stalled.

**Comment by frankhale** [comment]
@JakeChampion I did not say development has stalled but momentum has. We have an active Windows port as a pull request that is sitting without comment from Electrino author. We don't currently know if it will ever be merged or what concerns he may have with it in it's current form. Since original author is concerned with Mac, who will merge new code into the Windows port in the future? What will that process look like when or if this PR is merged. This is just one concern.

**Comment by amilajack** [comment]
I have been added as a collaborator 🎉  🎉  🎉

**Comment by frankhale** [comment]
This is great news, congratulations @amilajack!!!

**Comment by amilajack** [comment]
@frankhale Thanks! I'm not sure how good of a reviewer I'll be for this project. I don't know Obj-C or C#. I'll mostly merge PR's based on the feedback from others

**Comment by norman784** [comment]
we need at least one collaborator for each platform

**Comment by frankhale** [comment]
@norman784 agree, I think for the Windows port it should be https://github.com/tht13 since he submitted the PR for this.

**Comment by pojala** [comment]
Hi all!

Apologies again for my absence. I feel bad for leaving the impression that the project is adrift. I've just been hopelessly swamped over the past month. (If I had understood beforehand that there would be this level of interest in Electrino, I might have chosen a better timing to release the initial version... :))

Thanks very much to @amilajack for getting in touch and prodding me in the right direction.

I'd be very happy to add as collaborator anyone who wants to take charge of a particular platform!
