### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by DutchKevv** [pojala/electrino#2]
Hi there! 

Im building a relative heavy app (TradeJS), but with minimal electron requirements (so in a way perfect for Electrino). 

Only requirement I have is to open multiple windows.

Is it possible to make a performance comparison with some standars JS tests? Like kraken etc. 

Maybe it's no use, cause there are already existing benchmarks between chrome and default OS JS engines, but still it would be wise to mention it I think, because performance is one of the downsides in Electron/Web-Wrappers :)

Thanks!!!!

**Comment by jbergstroem** [comment]
Is there something that makes you unable to run these tests outside of the Electrino scope? I don't seem them being related. Just run kraken in your safari versus whatever v8 version that corresponds to electron.

**Comment by pojala** [comment]
Yes, the JavaScript engine in Safari is the same one as Electrino is using, so I would assume benchmark results are identical.

@DutchKevv If you have a list of Electron APIs your app needs, let me know! I'm planning to compile a suggested roadmap soon.
