### ISSUE TITLE
How To Compile

### ISSUE THREAD

**Issue by AnonymousXC** [pojala/electrino#31]
Hi, 
Could anyone tell how can we run the app that we are developing for debugging.
Like electron has :- `electron .`
What's for electrino :-  `     `
&&
Could anyone also tell that how can we compile our app for windows and mac.

**Comment by CitrusFruits** [comment]
I'm pretty sure this project is abandoned. If you want to see something similar you could check out https://tauri.studio/.

**Comment by AnonymousXC** [comment]
Thanks @CitrusFruits 
Its looks like. This is a cool idea as electron is really heavy for building small apps.
